name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: "Batch size"
        required: true
        default: "10"
        type: string

jobs:
  batch_logic:
    runs-on: ubuntu-latest
    outputs:
      batch_array: ${{ steps.batch_logic.outputs.BATCH_ARRAY }}
    steps:
      - name: Batch logic
        id: batch_logic
        run: |
          BATCH_ARRAY='["1", "2", "3", "4", "5"]'
          echo "BATCH_ARRAY=$BATCH_ARRAY" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: batch_logic
    strategy:
      matrix:
        batch_array: ${{ fromJson(needs.batch_logic.outputs.batch_array) }}
    steps:
      - name: Run tests
        run: |
          echo "Running tests for batch ${{ matrix.batch_array }}"
